version: '3.8'

services:
  weather:
    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      - VITE_API_URL

    volumes:
      - .:/usr/app
      - /usr/app/node_modules

    ports:
      - 3000:3000
